#!/usr/bin/env bash
#A Bash script that pings an IP address passed as an argument
#Accepts a string as an argument
#Ping the IP 5 times
if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 $1
