#!/usr/bin/env bash
# Check if an IP address argument is provided
# Ping the IP address 5 times and display the results
if [ "$#" -ne 1 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi
ping -c 5 "$1"